name: Test

run-name: test

on: 
  workflow_dispatch:

jobs:
  delete:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      
      - name: Test
        run: |
          echo "test"
